# Generated by Django 4.2.4 on 2023-09-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_app.productcategory')),
            ],
        ),
    ]
